import type { Exercise, ExerciseCategory, MovementPattern, Difficulty, InjuryType } from "@/types";

// Helper to create exercises concisely
function ex(
  id: string,
  name: string,
  category: ExerciseCategory,
  movement: MovementPattern,
  difficulty: Difficulty,
  equipment: string[],
  muscleGroups: string[],
  riskyFor: InjuryType[] = []
): Exercise {
  return {
    id, name, category, movement, difficulty, equipment, muscleGroups,
    description: "", cues: [], riskyFor,
  };
}

export const exercises: Exercise[] = [
  // === STRENGTH (80) ===
  ex("s01","Back Squat","strength","squat","intermediate",["barbell"],["quads","glutes"],["knee","lower_back"]),
  ex("s02","Front Squat","strength","squat","intermediate",["barbell"],["quads","core"],["knee","wrist"]),
  ex("s03","Goblet Squat","strength","squat","beginner",["kettlebell"],["quads","glutes"],[]),
  ex("s04","Bulgarian Split Squat","strength","lunge","intermediate",["dumbbell"],["quads","glutes"],["knee"]),
  ex("s05","Deadlift","strength","hinge","intermediate",["barbell"],["hamstrings","back","glutes"],["lower_back"]),
  ex("s06","Romanian Deadlift","strength","hinge","intermediate",["barbell"],["hamstrings","glutes"],["lower_back"]),
  ex("s07","Sumo Deadlift","strength","hinge","intermediate",["barbell"],["hamstrings","adductors"],["lower_back","hip"]),
  ex("s08","Trap Bar Deadlift","strength","hinge","beginner",["trap bar"],["quads","hamstrings"],[]),
  ex("s09","Bench Press","strength","push","intermediate",["barbell","bench"],["chest","triceps"],["shoulder"]),
  ex("s10","Incline Bench Press","strength","push","intermediate",["barbell","bench"],["upper chest","shoulders"],["shoulder"]),
  ex("s11","Dumbbell Bench Press","strength","push","beginner",["dumbbell","bench"],["chest","triceps"],["shoulder"]),
  ex("s12","Floor Press","strength","push","beginner",["dumbbell"],["chest","triceps"],[]),
  ex("s13","Overhead Press","strength","push","intermediate",["barbell"],["shoulders","triceps"],["shoulder","neck"]),
  ex("s14","Dumbbell Shoulder Press","strength","push","beginner",["dumbbell"],["shoulders","triceps"],["shoulder"]),
  ex("s15","Push Press","strength","push","intermediate",["barbell"],["shoulders","legs"],["shoulder"]),
  ex("s16","Barbell Row","strength","pull","intermediate",["barbell"],["back","biceps"],["lower_back"]),
  ex("s17","Dumbbell Row","strength","pull","beginner",["dumbbell","bench"],["back","biceps"],[]),
  ex("s18","Pendlay Row","strength","pull","advanced",["barbell"],["back","biceps"],["lower_back"]),
  ex("s19","Pull-Up","strength","pull","intermediate",["pull-up bar"],["back","biceps"],["shoulder","elbow"]),
  ex("s20","Chin-Up","strength","pull","intermediate",["pull-up bar"],["back","biceps"],["elbow"]),
  ex("s21","Lat Pulldown","strength","pull","beginner",["cable machine"],["back","biceps"],[]),
  ex("s22","Seated Cable Row","strength","pull","beginner",["cable machine"],["back","biceps"],[]),
  ex("s23","Hip Thrust","strength","hinge","beginner",["barbell","bench"],["glutes","hamstrings"],[]),
  ex("s24","Walking Lunge","strength","lunge","beginner",["dumbbell"],["quads","glutes"],["knee"]),
  ex("s25","Step-Up","strength","lunge","beginner",["dumbbell","box"],["quads","glutes"],["knee"]),
  ex("s26","Leg Press","strength","squat","beginner",["leg press"],["quads","glutes"],["knee"]),
  ex("s27","Leg Curl","strength","hinge","beginner",["machine"],["hamstrings"],[]),
  ex("s28","Leg Extension","strength","squat","beginner",["machine"],["quads"],["knee"]),
  ex("s29","Calf Raise","strength","squat","beginner",["barbell"],["calves"],[]),
  ex("s30","Face Pull","strength","pull","beginner",["cable machine","band"],["rear delts","rotator cuff"],[]),
  ex("s31","Lateral Raise","strength","push","beginner",["dumbbell"],["shoulders"],["shoulder"]),
  ex("s32","Bicep Curl","strength","pull","beginner",["dumbbell"],["biceps"],["elbow"]),
  ex("s33","Tricep Extension","strength","push","beginner",["dumbbell","cable machine"],["triceps"],["elbow"]),
  ex("s34","Dip","strength","push","intermediate",["parallel bars"],["chest","triceps"],["shoulder"]),
  ex("s35","Weighted Pull-Up","strength","pull","advanced",["pull-up bar","weight belt"],["back","biceps"],["shoulder"]),
  ex("s36","Rack Pull","strength","hinge","intermediate",["barbell","rack"],["back","hamstrings"],["lower_back"]),
  ex("s37","Good Morning","strength","hinge","intermediate",["barbell"],["hamstrings","back"],["lower_back"]),
  ex("s38","Zercher Squat","strength","squat","advanced",["barbell"],["quads","core"],["elbow"]),
  ex("s39","Pause Squat","strength","squat","advanced",["barbell"],["quads","glutes"],["knee","lower_back"]),
  ex("s40","Deficit Deadlift","strength","hinge","advanced",["barbell"],["hamstrings","back"],["lower_back"]),
  ex("s41","Single-Leg Deadlift","strength","hinge","intermediate",["kettlebell"],["hamstrings","glutes"],["ankle"]),
  ex("s42","Farmer Carry","strength","carry","beginner",["dumbbell","kettlebell"],["grip","core","traps"],[]),
  ex("s43","Suitcase Carry","strength","carry","intermediate",["kettlebell"],["obliques","grip"],[]),
  ex("s44","Overhead Carry","strength","carry","advanced",["kettlebell"],["shoulders","core"],["shoulder"]),
  ex("s45","Turkish Get-Up","strength","rotation","advanced",["kettlebell"],["full body"],["shoulder","wrist"]),
  ex("s46","Landmine Press","strength","push","beginner",["barbell","landmine"],["shoulders","chest"],[]),
  ex("s47","Landmine Row","strength","pull","beginner",["barbell","landmine"],["back","biceps"],[]),
  ex("s48","Cable Fly","strength","push","beginner",["cable machine"],["chest"],[]),
  ex("s49","Reverse Fly","strength","pull","beginner",["dumbbell"],["rear delts"],[]),
  ex("s50","Shrug","strength","pull","beginner",["barbell","dumbbell"],["traps"],[]),
  ex("s51","Upright Row","strength","pull","intermediate",["barbell"],["traps","shoulders"],["shoulder","wrist"]),
  ex("s52","Arnold Press","strength","push","intermediate",["dumbbell"],["shoulders"],[]),
  ex("s53","Close-Grip Bench","strength","push","intermediate",["barbell","bench"],["triceps","chest"],["shoulder"]),
  ex("s54","Skull Crusher","strength","push","intermediate",["barbell","bench"],["triceps"],["elbow"]),
  ex("s55","Hammer Curl","strength","pull","beginner",["dumbbell"],["biceps","forearms"],[]),
  ex("s56","Preacher Curl","strength","pull","beginner",["barbell","preacher bench"],["biceps"],["elbow"]),
  ex("s57","Cable Curl","strength","pull","beginner",["cable machine"],["biceps"],[]),
  ex("s58","Tricep Pushdown","strength","push","beginner",["cable machine"],["triceps"],[]),
  ex("s59","Overhead Tricep Ext","strength","push","beginner",["dumbbell"],["triceps"],["shoulder","elbow"]),
  ex("s60","Glute Bridge","strength","hinge","beginner",["bodyweight"],["glutes"],[]),
  ex("s61","Box Squat","strength","squat","intermediate",["barbell","box"],["quads","glutes"],[]),
  ex("s62","Safety Bar Squat","strength","squat","intermediate",["safety squat bar"],["quads","glutes"],[]),
  ex("s63","Cable Lateral Raise","strength","push","beginner",["cable machine"],["shoulders"],[]),
  ex("s64","Chest Supported Row","strength","pull","beginner",["dumbbell","incline bench"],["back"],[]),
  ex("s65","T-Bar Row","strength","pull","intermediate",["t-bar"],["back","biceps"],["lower_back"]),
  ex("s66","Meadows Row","strength","pull","intermediate",["barbell","landmine"],["back","biceps"],[]),
  ex("s67","Snatch Grip Deadlift","strength","hinge","advanced",["barbell"],["back","traps","hamstrings"],["lower_back"]),
  ex("s68","Hack Squat","strength","squat","intermediate",["hack squat machine"],["quads"],[]),
  ex("s69","Sissy Squat","strength","squat","advanced",["bodyweight"],["quads"],["knee"]),
  ex("s70","Nordic Curl","strength","hinge","advanced",["bodyweight"],["hamstrings"],["knee"]),
  ex("s71","Reverse Lunge","strength","lunge","beginner",["dumbbell"],["quads","glutes"],[]),
  ex("s72","Lateral Lunge","strength","lunge","beginner",["bodyweight"],["adductors","quads"],["knee"]),
  ex("s73","Pistol Squat","strength","squat","advanced",["bodyweight"],["quads","glutes"],["knee","ankle"]),
  ex("s74","Weighted Dip","strength","push","advanced",["parallel bars","weight belt"],["chest","triceps"],["shoulder"]),
  ex("s75","Muscle-Up","strength","pull","elite",["pull-up bar"],["back","chest","triceps"],["shoulder","wrist"]),
  ex("s76","Handstand Push-Up","strength","push","elite",["wall"],["shoulders","triceps"],["shoulder","wrist","neck"]),
  ex("s77","Ring Dip","strength","push","advanced",["rings"],["chest","triceps"],["shoulder"]),
  ex("s78","Ring Row","strength","pull","beginner",["rings"],["back","biceps"],[]),
  ex("s79","Inverted Row","strength","pull","beginner",["barbell","rack"],["back","biceps"],[]),
  ex("s80","GHD Hip Extension","strength","hinge","intermediate",["GHD"],["hamstrings","glutes"],["lower_back"]),

  // === CONDITIONING (50) ===
  ex("c01","Assault Bike Intervals","conditioning","gait","intermediate",["assault bike"],["full body"],[]),
  ex("c02","Rowing Intervals","conditioning","gait","intermediate",["rower"],["full body"],[]),
  ex("c03","Ski Erg Intervals","conditioning","gait","intermediate",["ski erg"],["back","shoulders"],[]),
  ex("c04","Box Jump","conditioning","squat","intermediate",["plyo box"],["quads","glutes"],["knee","ankle"]),
  ex("c05","Burpee","conditioning","push","intermediate",["bodyweight"],["full body"],["wrist","shoulder"]),
  ex("c06","Thruster","conditioning","squat","intermediate",["barbell"],["full body"],["shoulder","knee"]),
  ex("c07","Wall Ball","conditioning","squat","beginner",["medicine ball"],["quads","shoulders"],[]),
  ex("c08","Kettlebell Swing","conditioning","hinge","beginner",["kettlebell"],["glutes","hamstrings","core"],["lower_back"]),
  ex("c09","Battle Ropes","conditioning","push","beginner",["battle ropes"],["shoulders","arms","core"],["shoulder"]),
  ex("c10","Med Ball Slam","conditioning","hinge","beginner",["slam ball"],["core","shoulders"],[]),
  ex("c11","Box Step-Over","conditioning","lunge","beginner",["plyo box"],["quads","glutes"],[]),
  ex("c12","Jumping Lunges","conditioning","lunge","intermediate",["bodyweight"],["quads","glutes"],["knee"]),
  ex("c13","Mountain Climbers","conditioning","gait","beginner",["bodyweight"],["core","hip flexors"],[]),
  ex("c14","Jump Rope","conditioning","gait","beginner",["jump rope"],["calves","coordination"],["ankle"]),
  ex("c15","Double Unders","conditioning","gait","intermediate",["jump rope"],["calves","coordination"],["ankle"]),
  ex("c16","KB Snatch","conditioning","hinge","advanced",["kettlebell"],["full body"],["shoulder","wrist"]),
  ex("c17","KB Clean & Jerk","conditioning","hinge","advanced",["kettlebell"],["full body"],["shoulder","wrist"]),
  ex("c18","Sled Push","conditioning","gait","beginner",["sled"],["quads","glutes"],[]),
  ex("c19","Sled Pull","conditioning","gait","beginner",["sled"],["hamstrings","back"],[]),
  ex("c20","Tire Flip","conditioning","hinge","advanced",["tire"],["full body"],["lower_back"]),
  ex("c21","Rope Climb","conditioning","pull","advanced",["climbing rope"],["back","grip"],["shoulder"]),
  ex("c22","Power Clean","conditioning","hinge","advanced",["barbell"],["full body"],["wrist","shoulder"]),
  ex("c23","Hang Clean","conditioning","hinge","intermediate",["barbell"],["full body"],["wrist"]),
  ex("c24","Clean & Jerk","conditioning","hinge","advanced",["barbell"],["full body"],["shoulder","wrist"]),
  ex("c25","Snatch","conditioning","hinge","elite",["barbell"],["full body"],["shoulder","wrist"]),
  ex("c26","Power Snatch","conditioning","hinge","advanced",["barbell"],["full body"],["shoulder","wrist"]),
  ex("c27","Sumo Deadlift High Pull","conditioning","hinge","intermediate",["barbell"],["full body"],["shoulder"]),
  ex("c28","Devil Press","conditioning","hinge","advanced",["dumbbell"],["full body"],["shoulder"]),
  ex("c29","Man Maker","conditioning","push","advanced",["dumbbell"],["full body"],["shoulder","wrist"]),
  ex("c30","Bike Erg Sprint","conditioning","gait","intermediate",["bike erg"],["legs"],[]),
  ex("c31","Air Squat","conditioning","squat","beginner",["bodyweight"],["quads","glutes"],[]),
  ex("c32","Tuck Jump","conditioning","squat","intermediate",["bodyweight"],["quads","core"],["knee"]),
  ex("c33","Broad Jump","conditioning","squat","intermediate",["bodyweight"],["quads","glutes"],["ankle"]),
  ex("c34","Lateral Hop","conditioning","gait","beginner",["bodyweight"],["calves","ankles"],["ankle"]),
  ex("c35","Bear Crawl","conditioning","gait","beginner",["bodyweight"],["shoulders","core"],["wrist"]),
  ex("c36","Crab Walk","conditioning","gait","beginner",["bodyweight"],["triceps","core"],["wrist"]),
  ex("c37","Sandbag Clean","conditioning","hinge","intermediate",["sandbag"],["full body"],[]),
  ex("c38","Sandbag Carry","conditioning","carry","beginner",["sandbag"],["core","grip"],[]),
  ex("c39","Ball Over Shoulder","conditioning","hinge","intermediate",["atlas stone","sandbag"],["full body"],["lower_back"]),
  ex("c40","Echo Bike EMOM","conditioning","gait","intermediate",["assault bike"],["full body"],[]),
  ex("c41","Shuttle Run","conditioning","gait","beginner",["bodyweight"],["legs","agility"],[]),
  ex("c42","Agility Ladder","conditioning","gait","beginner",["agility ladder"],["calves","coordination"],[]),
  ex("c43","High Knees","conditioning","gait","beginner",["bodyweight"],["hip flexors","core"],[]),
  ex("c44","Butt Kicks","conditioning","gait","beginner",["bodyweight"],["hamstrings"],[]),
  ex("c45","Sprawl","conditioning","push","intermediate",["bodyweight"],["full body"],[]),
  ex("c46","KB Goblet Thruster","conditioning","squat","beginner",["kettlebell"],["full body"],[]),
  ex("c47","Dumbbell Snatch","conditioning","hinge","intermediate",["dumbbell"],["full body"],["shoulder"]),
  ex("c48","Hang Power Clean","conditioning","hinge","intermediate",["barbell"],["full body"],["wrist"]),
  ex("c49","Push-Up","conditioning","push","beginner",["bodyweight"],["chest","triceps"],["wrist","shoulder"]),
  ex("c50","Clapping Push-Up","conditioning","push","advanced",["bodyweight"],["chest","triceps"],["wrist","shoulder"]),

  // === ENDURANCE (30) ===
  ex("e01","5K Run","endurance","gait","beginner",["bodyweight"],["legs","cardio"],["knee","ankle"]),
  ex("e02","10K Run","endurance","gait","intermediate",["bodyweight"],["legs","cardio"],["knee","ankle"]),
  ex("e03","Tempo Run","endurance","gait","intermediate",["bodyweight"],["legs","cardio"],["knee"]),
  ex("e04","Interval Run 400m","endurance","gait","intermediate",["bodyweight"],["legs","cardio"],[]),
  ex("e05","Hill Sprints","endurance","gait","advanced",["bodyweight"],["legs","glutes"],[]),
  ex("e06","Stair Climb","endurance","gait","beginner",["stairs"],["quads","calves"],[]),
  ex("e07","2K Row","endurance","gait","intermediate",["rower"],["full body"],[]),
  ex("e08","5K Row","endurance","gait","advanced",["rower"],["full body"],[]),
  ex("e09","30min Bike","endurance","gait","beginner",["assault bike"],["legs"],[]),
  ex("e10","Assault Bike 10cal EMOM","endurance","gait","intermediate",["assault bike"],["full body"],[]),
  ex("e11","Long Swim","endurance","gait","intermediate",["pool"],["full body"],["shoulder"]),
  ex("e12","Treadmill Walk Incline","endurance","gait","beginner",["treadmill"],["legs","glutes"],[]),
  ex("e13","Fartlek Run","endurance","gait","intermediate",["bodyweight"],["legs","cardio"],[]),
  ex("e14","Track 800m Repeats","endurance","gait","advanced",["bodyweight"],["legs","cardio"],[]),
  ex("e15","Steady-State Row 20min","endurance","gait","beginner",["rower"],["full body"],[]),
  ex("e16","Mixed Modal 30min","endurance","gait","intermediate",["various"],["full body"],[]),
  ex("e17","Trail Run","endurance","gait","intermediate",["bodyweight"],["legs","balance"],["ankle"]),
  ex("e18","Sled Push 400m","endurance","gait","advanced",["sled"],["quads","conditioning"],[]),
  ex("e19","Farmers Walk 400m","endurance","carry","intermediate",["dumbbell"],["grip","core"],[]),
  ex("e20","Ruck Walk","endurance","gait","beginner",["backpack"],["legs","back"],[]),
  ex("e21","Bike Erg 5K","endurance","gait","intermediate",["bike erg"],["legs"],[]),
  ex("e22","Ski Erg 2K","endurance","gait","intermediate",["ski erg"],["back","arms"],[]),
  ex("e23","Jacob's Ladder","endurance","gait","intermediate",["jacob's ladder"],["full body"],[]),
  ex("e24","VersaClimber","endurance","gait","advanced",["versaclimber"],["full body"],[]),
  ex("e25","Zone 2 Run 45min","endurance","gait","beginner",["bodyweight"],["legs","cardio"],[]),
  ex("e26","Recovery Jog","endurance","gait","beginner",["bodyweight"],["legs"],[]),
  ex("e27","Sprint 100m x10","endurance","gait","advanced",["bodyweight"],["legs","power"],[]),
  ex("e28","Bike Tabata","endurance","gait","advanced",["assault bike"],["legs"],[]),
  ex("e29","Row Tabata","endurance","gait","advanced",["rower"],["full body"],[]),
  ex("e30","Swim Intervals","endurance","gait","advanced",["pool"],["full body"],["shoulder"]),

  // === MOBILITY (40) ===
  ex("m01","Cat-Cow","mobility","rotation","beginner",["bodyweight"],["spine"],[]),
  ex("m02","World's Greatest Stretch","mobility","lunge","beginner",["bodyweight"],["hip flexors","thoracic"],[]),
  ex("m03","90/90 Hip Stretch","mobility","rotation","beginner",["bodyweight"],["hips"],[]),
  ex("m04","Pigeon Stretch","mobility","static","beginner",["bodyweight"],["hips","glutes"],["knee"]),
  ex("m05","Couch Stretch","mobility","static","beginner",["bodyweight"],["hip flexors","quads"],[]),
  ex("m06","Deep Squat Hold","mobility","squat","beginner",["bodyweight"],["hips","ankles"],[]),
  ex("m07","Thoracic Rotation","mobility","rotation","beginner",["bodyweight"],["thoracic spine"],[]),
  ex("m08","Shoulder Dislocate","mobility","rotation","beginner",["PVC pipe","band"],["shoulders"],["shoulder"]),
  ex("m09","Band Pull Apart","mobility","pull","beginner",["band"],["rear delts","scapula"],[]),
  ex("m10","Foam Roll Thoracic","mobility","static","beginner",["foam roller"],["thoracic spine"],[]),
  ex("m11","Foam Roll IT Band","mobility","static","beginner",["foam roller"],["IT band"],[]),
  ex("m12","Foam Roll Quads","mobility","static","beginner",["foam roller"],["quads"],[]),
  ex("m13","Foam Roll Lats","mobility","static","beginner",["foam roller"],["lats"],[]),
  ex("m14","Ankle Mobilization","mobility","squat","beginner",["band"],["ankles"],[]),
  ex("m15","Hip CARs","mobility","rotation","beginner",["bodyweight"],["hips"],[]),
  ex("m16","Shoulder CARs","mobility","rotation","beginner",["bodyweight"],["shoulders"],[]),
  ex("m17","Jefferson Curl","mobility","hinge","intermediate",["bodyweight","light dumbbell"],["hamstrings","spine"],["lower_back"]),
  ex("m18","Pancake Stretch","mobility","hinge","intermediate",["bodyweight"],["adductors","hamstrings"],[]),
  ex("m19","Frog Stretch","mobility","static","beginner",["bodyweight"],["adductors","hips"],[]),
  ex("m20","Wall Slide","mobility","push","beginner",["wall"],["shoulders","scapula"],[]),
  ex("m21","Supine Hamstring Stretch","mobility","hinge","beginner",["band"],["hamstrings"],[]),
  ex("m22","Prone Scorpion","mobility","rotation","beginner",["bodyweight"],["thoracic","hip flexors"],[]),
  ex("m23","Thread the Needle","mobility","rotation","beginner",["bodyweight"],["thoracic spine"],[]),
  ex("m24","Lying Spinal Twist","mobility","rotation","beginner",["bodyweight"],["spine","obliques"],[]),
  ex("m25","Downward Dog","mobility","push","beginner",["bodyweight"],["hamstrings","shoulders"],[]),
  ex("m26","Upward Dog","mobility","push","beginner",["bodyweight"],["hip flexors","chest"],[]),
  ex("m27","Child's Pose","mobility","static","beginner",["bodyweight"],["back","shoulders"],[]),
  ex("m28","Banded Hip Distraction","mobility","squat","beginner",["band"],["hips"],[]),
  ex("m29","Wrist Circles","mobility","rotation","beginner",["bodyweight"],["wrists"],[]),
  ex("m30","Neck Circles","mobility","rotation","beginner",["bodyweight"],["neck"],[]),
  ex("m31","Lacrosse Ball Pec","mobility","static","beginner",["lacrosse ball"],["pecs"],[]),
  ex("m32","Lacrosse Ball Glute","mobility","static","beginner",["lacrosse ball"],["glutes"],[]),
  ex("m33","Half-Kneeling Hip Flex Stretch","mobility","lunge","beginner",["bodyweight"],["hip flexors"],[]),
  ex("m34","Standing Quad Stretch","mobility","static","beginner",["bodyweight"],["quads"],[]),
  ex("m35","Calf Stretch","mobility","static","beginner",["wall"],["calves"],[]),
  ex("m36","Seated Forward Fold","mobility","hinge","beginner",["bodyweight"],["hamstrings","back"],[]),
  ex("m37","Butterfly Stretch","mobility","static","beginner",["bodyweight"],["adductors"],[]),
  ex("m38","Cross-Body Shoulder Stretch","mobility","static","beginner",["bodyweight"],["shoulders"],[]),
  ex("m39","Tricep Stretch","mobility","static","beginner",["bodyweight"],["triceps"],[]),
  ex("m40","Side Bend Stretch","mobility","static","beginner",["bodyweight"],["obliques","lats"],[]),

  // === CORE (30) ===
  ex("co01","Plank","core","static","beginner",["bodyweight"],["core"],[]),
  ex("co02","Side Plank","core","static","beginner",["bodyweight"],["obliques"],[]),
  ex("co03","Dead Bug","core","static","beginner",["bodyweight"],["core","hip flexors"],[]),
  ex("co04","Bird Dog","core","static","beginner",["bodyweight"],["core","back"],[]),
  ex("co05","Hollow Body Hold","core","static","intermediate",["bodyweight"],["core"],[]),
  ex("co06","V-Up","core","static","intermediate",["bodyweight"],["core","hip flexors"],[]),
  ex("co07","Hanging Knee Raise","core","static","intermediate",["pull-up bar"],["core","hip flexors"],["shoulder"]),
  ex("co08","Hanging Leg Raise","core","static","advanced",["pull-up bar"],["core"],["shoulder"]),
  ex("co09","Toes-to-Bar","core","static","advanced",["pull-up bar"],["core"],["shoulder"]),
  ex("co10","Ab Wheel Rollout","core","static","intermediate",["ab wheel"],["core"],["lower_back"]),
  ex("co11","Pallof Press","core","rotation","beginner",["cable machine","band"],["core","obliques"],[]),
  ex("co12","Russian Twist","core","rotation","beginner",["bodyweight","medicine ball"],["obliques"],[]),
  ex("co13","Bicycle Crunch","core","rotation","beginner",["bodyweight"],["obliques","core"],[]),
  ex("co14","Flutter Kicks","core","static","beginner",["bodyweight"],["core","hip flexors"],[]),
  ex("co15","Leg Lower","core","static","intermediate",["bodyweight"],["core"],[]),
  ex("co16","Dragon Flag","core","static","elite",["bench"],["core"],["lower_back"]),
  ex("co17","L-Sit","core","static","advanced",["parallel bars"],["core","hip flexors"],[]),
  ex("co18","Suitcase Deadlift","core","hinge","intermediate",["kettlebell"],["core","obliques"],[]),
  ex("co19","Farmer Walk Hold","core","carry","beginner",["dumbbell"],["core","grip"],[]),
  ex("co20","Cable Woodchop","core","rotation","beginner",["cable machine"],["obliques","core"],[]),
  ex("co21","Med Ball Russian Twist","core","rotation","beginner",["medicine ball"],["obliques"],[]),
  ex("co22","Plank Pull-Through","core","static","intermediate",["kettlebell"],["core"],[]),
  ex("co23","Copenhagen Plank","core","static","advanced",["bench"],["adductors","core"],[]),
  ex("co24","Stir the Pot","core","rotation","intermediate",["stability ball"],["core"],[]),
  ex("co25","Bear Crawl Hold","core","static","beginner",["bodyweight"],["core","shoulders"],[]),
  ex("co26","Suitcase Walk","core","carry","intermediate",["kettlebell"],["obliques","grip"],[]),
  ex("co27","Anti-Rotation Press","core","rotation","intermediate",["cable machine"],["core","obliques"],[]),
  ex("co28","GHD Sit-Up","core","static","intermediate",["GHD"],["core","hip flexors"],["lower_back"]),
  ex("co29","Hanging Windshield Wiper","core","rotation","elite",["pull-up bar"],["obliques"],["shoulder"]),
  ex("co30","Plank Shoulder Tap","core","static","beginner",["bodyweight"],["core","shoulders"],[]),

  // === RECOVERY (20) ===
  ex("r01","Light Walk","recovery","gait","beginner",["bodyweight"],["full body"],[]),
  ex("r02","Easy Bike 15min","recovery","gait","beginner",["bike"],["legs"],[]),
  ex("r03","Easy Row 15min","recovery","gait","beginner",["rower"],["full body"],[]),
  ex("r04","Yoga Flow","recovery","rotation","beginner",["bodyweight"],["full body"],[]),
  ex("r05","Full Body Foam Roll","recovery","static","beginner",["foam roller"],["full body"],[]),
  ex("r06","Diaphragmatic Breathing","recovery","static","beginner",["bodyweight"],["core","recovery"],[]),
  ex("r07","Box Breathing","recovery","static","beginner",["bodyweight"],["recovery"],[]),
  ex("r08","Contract-Relax Hamstrings","recovery","hinge","beginner",["bodyweight"],["hamstrings"],[]),
  ex("r09","Contract-Relax Shoulders","recovery","push","beginner",["bodyweight"],["shoulders"],[]),
  ex("r10","Supine Spinal Twist","recovery","rotation","beginner",["bodyweight"],["spine"],[]),
  ex("r11","Happy Baby","recovery","static","beginner",["bodyweight"],["hips"],[]),
  ex("r12","Legs Up The Wall","recovery","static","beginner",["wall"],["legs","recovery"],[]),
  ex("r13","Gentle Neck Stretch","recovery","static","beginner",["bodyweight"],["neck"],[]),
  ex("r14","Wrist Flexor Stretch","recovery","static","beginner",["bodyweight"],["wrists"],[]),
  ex("r15","Ankle Circles","recovery","rotation","beginner",["bodyweight"],["ankles"],[]),
  ex("r16","Progressive Muscle Relax","recovery","static","beginner",["bodyweight"],["full body"],[]),
  ex("r17","Self-Massage Ball Work","recovery","static","beginner",["lacrosse ball"],["full body"],[]),
  ex("r18","Band-Assisted Stretch","recovery","static","beginner",["band"],["full body"],[]),
  ex("r19","Crocodile Breathing","recovery","static","beginner",["bodyweight"],["diaphragm"],[]),
  ex("r20","Savasana","recovery","static","beginner",["bodyweight"],["recovery"],[]),

  // === HYROX (25) ===
  ex("h01","SkiErg 1000m","hyrox","gait","intermediate",["ski erg"],["back","arms"],[]),
  ex("h02","Sled Push 50m","hyrox","gait","intermediate",["sled"],["quads","glutes"],[]),
  ex("h03","Sled Pull 50m","hyrox","gait","intermediate",["sled"],["hamstrings","back"],[]),
  ex("h04","Burpee Broad Jump","hyrox","push","intermediate",["bodyweight"],["full body"],["wrist"]),
  ex("h05","Rowing 1000m","hyrox","gait","intermediate",["rower"],["full body"],[]),
  ex("h06","Farmer Carry 200m","hyrox","carry","intermediate",["kettlebell"],["grip","core"],[]),
  ex("h07","Sandbag Lunges 100m","hyrox","lunge","intermediate",["sandbag"],["quads","glutes"],["knee"]),
  ex("h08","Wall Balls 100 reps","hyrox","squat","intermediate",["medicine ball"],["quads","shoulders"],[]),
  ex("h09","HYROX Run 1K","hyrox","gait","intermediate",["bodyweight"],["legs","cardio"],[]),
  ex("h10","HYROX Simulation","hyrox","gait","advanced",["various"],["full body"],[]),
  ex("h11","Sled Push Intervals","hyrox","gait","intermediate",["sled"],["quads"],[]),
  ex("h12","Sled Pull Intervals","hyrox","gait","intermediate",["sled"],["back"],[]),
  ex("h13","SkiErg Intervals","hyrox","gait","intermediate",["ski erg"],["back","arms"],[]),
  ex("h14","Wall Ball EMOM","hyrox","squat","intermediate",["medicine ball"],["quads","shoulders"],[]),
  ex("h15","Burpee Broad Jump Intervals","hyrox","push","intermediate",["bodyweight"],["full body"],[]),
  ex("h16","Sandbag Over Shoulder","hyrox","hinge","intermediate",["sandbag"],["full body"],["lower_back"]),
  ex("h17","HYROX Pacing Run","hyrox","gait","intermediate",["bodyweight"],["legs"],[]),
  ex("h18","Transition Training","hyrox","gait","intermediate",["various"],["full body"],[]),
  ex("h19","HYROX Doubles Sim","hyrox","gait","advanced",["various"],["full body"],[]),
  ex("h20","Sled Sprint 25m","hyrox","gait","advanced",["sled"],["quads","power"],[]),
  ex("h21","KB Farmer Walk 100m","hyrox","carry","beginner",["kettlebell"],["grip","core"],[]),
  ex("h22","Sandbag Carry 100m","hyrox","carry","intermediate",["sandbag"],["core","grip"],[]),
  ex("h23","Run-Ski Transition","hyrox","gait","intermediate",["ski erg"],["full body"],[]),
  ex("h24","Run-Sled Transition","hyrox","gait","intermediate",["sled"],["full body"],[]),
  ex("h25","HYROX Recovery Protocol","hyrox","gait","beginner",["various"],["full body"],[]),

  // === DEKA (25) ===
  ex("d01","DEKA Ram Burpee","deka","push","intermediate",["ram"],["full body"],["wrist"]),
  ex("d02","DEKA Alt. Reverse Lunge","deka","lunge","beginner",["ram"],["quads","glutes"],[]),
  ex("d03","DEKA Row 500m","deka","gait","intermediate",["rower"],["full body"],[]),
  ex("d04","DEKA Med Ball Sit-Up Throw","deka","rotation","intermediate",["medicine ball"],["core"],["lower_back"]),
  ex("d05","DEKA Ski Erg 500m","deka","gait","intermediate",["ski erg"],["back","arms"],[]),
  ex("d06","DEKA Bike 20cal","deka","gait","intermediate",["assault bike"],["legs"],[]),
  ex("d07","DEKA Dead Ball Over Shoulder","deka","hinge","intermediate",["dead ball"],["full body"],["lower_back"]),
  ex("d08","DEKA Farmer Carry","deka","carry","beginner",["kettlebell"],["grip","core"],[]),
  ex("d09","DEKA Tank Push/Pull","deka","gait","intermediate",["tank"],["full body"],[]),
  ex("d10","DEKA Ram Squat","deka","squat","beginner",["ram"],["quads","glutes"],[]),
  ex("d11","DEKA Simulation Full","deka","gait","advanced",["various"],["full body"],[]),
  ex("d12","DEKA Zone 1-5","deka","gait","intermediate",["various"],["full body"],[]),
  ex("d13","DEKA Zone 6-10","deka","gait","intermediate",["various"],["full body"],[]),
  ex("d14","DEKA Strong","deka","gait","advanced",["various"],["full body"],[]),
  ex("d15","DEKA Fit","deka","gait","intermediate",["various"],["full body"],[]),
  ex("d16","Ram Burpee Intervals","deka","push","intermediate",["ram"],["full body"],[]),
  ex("d17","Reverse Lunge Intervals","deka","lunge","intermediate",["ram"],["quads"],[]),
  ex("d18","DEKA Transition Drill","deka","gait","intermediate",["various"],["full body"],[]),
  ex("d19","Dead Ball Slams","deka","hinge","beginner",["dead ball"],["core","power"],[]),
  ex("d20","DEKA Run 500m","deka","gait","beginner",["bodyweight"],["legs"],[]),
  ex("d21","Tank Sprint 25m","deka","gait","intermediate",["tank"],["full body"],[]),
  ex("d22","DEKA Mile Repeats","deka","gait","intermediate",["bodyweight"],["legs","cardio"],[]),
  ex("d23","DEKA Recovery Jog","deka","gait","beginner",["bodyweight"],["legs"],[]),
  ex("d24","DEKA Strength Block","deka","push","intermediate",["various"],["full body"],[]),
  ex("d25","DEKA Endurance Block","deka","gait","intermediate",["various"],["full body"],[]),
];

// Group exercises by category
export function groupByCategory(exs: Exercise[]): Record<ExerciseCategory, Exercise[]> {
  const groups: Record<string, Exercise[]> = {};
  for (const e of exs) {
    (groups[e.category] ??= []).push(e);
  }
  return groups as Record<ExerciseCategory, Exercise[]>;
}

// Search exercises
export function searchExercises(query: string, category?: ExerciseCategory): Exercise[] {
  const q = query.toLowerCase();
  return exercises.filter(
    (e) =>
      (!category || e.category === category) &&
      (e.name.toLowerCase().includes(q) ||
        e.muscleGroups.some((m) => m.toLowerCase().includes(q)) ||
        e.equipment.some((eq) => eq.toLowerCase().includes(q)))
  );
}
